### ISSUE TITLE
Metavault - issues

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#101]
https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/26/files#diff-16d341d6772401e45c3c87cbe24250b2fba9774b6010d5b3b074a686c40cb23aR35-R44

1) v3 positions should only consider active position only (in range)
2) token balance should be in raw amount (BIGINT) , currently its in real amount
3) you need to sum up the balances of the same asset before pushing to the output (sum both v3  + perps)

can you link the gh repo for the v3 + trades

**Comment by 0xroll** [comment]
@sdcrypt0 hi please check the above, and provide gh repo link for subgraph

**Comment by sdcrypt0** [comment]
Hi,
We fixed issues and open a pull request. Please check.
Do you need subgraph repositories or smart contract repositories?

**Comment by 0xroll** [comment]
> Hi @0xroll , We fixed issues and open a pull request. Please check. Do you need subgraph repositories or smart contract repositories?

the subgraph repo

**Comment by sdcrypt0** [comment]
i have added you to the repo. please refer here: https://github.com/metavaultorg/dex-subgraphs

**Comment by sdcrypt0** [comment]
@0xroll 
new pull request created for new requirements. 
https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/143
