### ISSUE TITLE
Gravitas - Pagination required

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#106]
hi @spider-g 

can you add in pagination so we dont miss out any data > 1000

https://github.com/delta-hq/l2-lxp-liquidity-reward/blob/main/adapters/gravita/src/index.ts#L52-L90

**Comment by spider-g** [comment]
Sure, here's the PR for that:
https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/111

Em ter., 7 de mai. de 2024 às 03:28, 0xroll ***@***.***>
escreveu:
