### ISSUE TITLE
Satori - Issues

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#119]
hey @miler012 

need your help to fix the current issues we have for Satori's adapter, your contracts are all private.

1) DEX : user's LP are not available 
2) Perps : adapter is returning alot more tvl than expected (comparing against defillama and the balances on the 2 contracts)

can you dm me to get these fixed? my telegram is @jh_onchain

**Comment by RamonReis** [comment]
We're also facing this error in production:
2024-05-09 18:40:27,245 ERROR root Response status: Too Many Requests
Current skip value:  30000
An error occurred for block: Error: Error fetching data from subgraph 
Status code: 429
Status Text: Too Many Requests
    at getUserTVLByBlock (/project/tvl_adapters/adapters/satori/dist/sdk/subgraphDetailsV2.js:28:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /project/tvl_adapters/adapters/satori/dist/index.js:55:28

**Comment by miler012** [comment]
https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/126
hi here is a merge request

**Comment by miler012** [comment]
https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/126
 add the dex tvl
