### ISSUE TITLE
MYX generation wrong data in outputdata.csv

### ISSUE THREAD

**Issue by nitish-91** [delta-hq/l2-lxp-liquidity-reward#144]
Run the adapter for block 4603301
1. The timestamp is returned as NaN.
2. The fields are not returned in expected order

**Comment by nitish-91** [comment]
@marvin6en please look into this

**Comment by marvin6en** [comment]
> Run the adapter for block 4603301
> 
> 1. The timestamp is returned as NaN.
> 2. The fields are not returned in expected order

A fix has been made, please merge this pr：https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/145
