### ISSUE TITLE
Interport - Adapter sending data for block 4595017 even when tried for other blocks

### ISSUE THREAD

**Issue by nitish-91** [delta-hq/l2-lxp-liquidity-reward#152]
Block tried - 
number,timestamp
4604499,1715857198

please check the code and make sure it is giving the right output

**Comment by nitish-91** [comment]
@bogdanuch  can you please check this

**Comment by dev-dozer** [comment]
@nitish-91 Hi! I've reviewed the issue and we implemented the necessary fixes. Please check the pull request here for the details: [PR #230](https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/230). Looking forward to your feedback!
