### ISSUE TITLE
XFAI - Ingestion is beginning from block  1141131 even when input block is 4604499

### ISSUE THREAD

**Issue by nitish-91** [delta-hq/l2-lxp-liquidity-reward#153]
Data should be returned for the block which is given as input

**Comment by notdian** [comment]
https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/139
this fixes it, the data is still valid, that's the last change of liquidity for that account, I made a change to return the specified block nevertheless

**Comment by nitish-91** [comment]
@notdian still seeing same issue. can you please test on your end and put the sample outputData.csv in PR
