### ISSUE TITLE
MYX - stale data from subgraph

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#157]
@marvin6en hi please check your subgraph, data seems stale . lastest data 15 hours ago

**Comment by marvin6en** [comment]
> @marvin6en hi please check your subgraph, data seems stale . lastest data 15 hours ago

No problem, there is no user interaction after this time, and indeed no new data is generated.

**Comment by 0xroll** [comment]
> > @marvin6en hi please check your subgraph, data seems stale . lastest data 15 hours ago
> 
> No problem, there is no user interaction after this time, and indeed no new data is generated.

the userLPStats entity need to return the latest user state as of block number X

we can discuss on tg too @jh_onchain

**Comment by marvin6en** [comment]
> > > @marvin6en hi please check your subgraph, data seems stale . lastest data 15 hours ago
> > 
> > 
> > No problem, there is no user interaction after this time, and indeed no new data is generated.
> 
> the userLPStats entity need to return the latest user state as of block number X
> 
> we can discuss on tg too @jh_onchain

@0xroll already fixed. https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/162
