### ISSUE TITLE
Metavault - issue

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#158]
hi @sdcrypt0 , just quick fixes here. 

change token mapping for eth - > weth address (lowercase)

also, can you share with me some transaction hash for perp to track liquidity? (deposit / withdrawals etc)

**Comment by sdcrypt0** [comment]
hi @0xroll 
 token mapping applied and created a new pull request #164
 
 Deposit Transaction: https://lineascan.build/tx/0x961d30d437ce8656cc709ffd2f1a3bdb164a6c34f7cb549fd05f6fda86291844
 
Withdrawal Transaction: https://lineascan.build/tx/0x5b5dd0c0114268218171a5a876e6257f3b83e5c3454b2a756f0bfb389fddb3ee

You can watch PoolDeposit, PoolWithdrawal events from Store Contract: https://lineascan.build/address/0xb514ee8a1e00b102ce2312048abcbc3e57bfed94

There are two assets on Store for now: ETH and USDC

**Comment by 0xroll** [comment]
@sdcrypt0 thanks for the quick response.

are there not much tvl on the perps side? can you share an address that has a decent amount of tvl in there
and are the perps indexed on debank as well?

**Comment by sdcrypt0** [comment]
@0xroll 

There was much more liquidity on older blocks but withdrawed. But enough for perps trading. 
V2, V3 pools has debank integration. Perps deposit, withdrawal doesn't have debank integration.

This account has 0.19 ETH on perps store: 0x44011805d7d0a6517cde184e6511071a7390047b
