### ISSUE TITLE
Davos - issues

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#168]
hi @xr9kayu 

is it live on linea? i cant see it on the website

![image](https://github.com/delta-hq/l2-lxp-liquidity-reward/assets/96259407/7bc03e37-f147-4898-b65f-5757dc16236f)

please go through the checklist.

token and addresses should be lowered case.

is davos like CDP protocol?

**Comment by gnosis2022** [comment]
@0xroll fix of the lowercase issue https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/188

**Comment by 0xroll** [comment]
@gnosis2022 are there not much tvl on davos? is it live already?

last checked there isnt much tvl

**Comment by henriquedias21** [comment]
![Screenshot 2024-05-30 at 10 50 05](https://github.com/delta-hq/l2-lxp-liquidity-reward/assets/132664761/296bf2d6-071a-4900-8314-e86be7990c21)
Yes, davos is a CDP protocol
And we're live on Linea
