### ISSUE TITLE
XY Finance - Issue

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#171]
hey @jaredWu0805 

quick question, why are the tvl so different from the contract's tvl?

https://lineascan.build/address/0xa5cb30e5d30a9843b6481ffd8d8d35dded3a3251
https://lineascan.build/address/0x9d90cfa17f3afcee2505b3e9d75113e6f5c9e843

85 eth and 38k usdc

vs

26 eth and 14k+ usdc on adapter response

testing with the following blocks :
4830068
4827668
4826468

**Comment by peterfangtw** [comment]
@0xroll 
- the response in the adapter only calculates the actual deposit value
- the value you see in the contracts includes values coming from our cross-chain swap 

so everything is working as expected, let me know if you need more clarifications 👍
