### ISSUE TITLE
3ADAO - Issues

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#178]
hi @bytes0xcr6 

1) can you make sure you are aggregating the token amount? they should be grouped on user , asset level of each timestamp/block
2) seems like 3aDAO accepts mendi receipt tokens, can you make it to return actual underlying asset balance instead

**Comment by 0xroll** [comment]
@bytes0xcr6 

1 ) aggregate user,token level. they are showing as multiple entries now

![image](https://github.com/delta-hq/l2-lxp-liquidity-reward/assets/96259407/f8c2abd7-8497-4785-92d5-009272c6b8e3)

2) adapters are tracking cToken flows, so since it is deposited into your vault, mendi's adapter will not reflect this amount. hence will need you to modify your adapter to provide the underlying balances of these users

**Comment by bytes0xcr6** [comment]
@0xroll 

1. Could you give us an example of your hourly_blocks.csv? Please. Ours for testing looks like:
![image](https://github.com/delta-hq/l2-lxp-liquidity-reward/assets/102038261/fadd3c6a-06f3-4faf-a3e5-c38c667efced)

and the output looks like what you are looking for:
![image](https://github.com/delta-hq/l2-lxp-liquidity-reward/assets/102038261/63572e30-fa7d-4e05-9625-8e51b949f093)


2. No problem. We are working on that.

**Comment by bytes0xcr6** [comment]
@0xroll PR with the fix: https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/189
