### ISSUE TITLE
XFAI - issues

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#180]
@notdian 

positions are still not displaying correctly.

example : 4918856

user have already removed liquidity , but adapter still returning results for this user

![image](https://github.com/delta-hq/l2-lxp-liquidity-reward/assets/96259407/1eb009d0-de2f-4d83-97aa-3c6e80a6c0e2)

https://lineascan.build/token/0xbdb4b1abb18cc982206155d852afc400ba47136b?a=0xfeedfe9c2acb949ef80b0fa714e282d66bd2f955

**Comment by notdian** [comment]
This is fixed now, indexer had inserted duplicate rows, deleted duplicates and also added a unique constraint on `txHash`

**Comment by 0xroll** [comment]
@notdian 

https://lineascan.build/token/0xbdb4b1abb18cc982206155d852afc400ba47136b?a=0xe3EA3e3CB1a83F8d414290Eef0Ec39182CBE91aD

block 4923656 returning user still have balances
