### ISSUE TITLE
Linehub - Issues

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#265]
hi @sdcrypt0 the latest pr merged is causing issues . can you look into it?

i have reverted the pr for now

https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/248

**Comment by sdcrypt0** [comment]
Hi @0xroll 
What is the issue? It's same as metavault adapter. Only subgraph addresses are different.

**Comment by 0xroll** [comment]
@sdcrypt0 

after the new pr merged, the adapter has been failing. seems like there is no output in the csv.

check logs here : 
[dag_id=dag_linea_tvl_snapshot_ingestion_run_id=scheduled__2024-07-18T09_00_00+00_00_task_id=linehub_tvl_data_ingestion_attempt=4.log](https://github.com/user-attachments/files/16283902/dag_id.dag_linea_tvl_snapshot_ingestion_run_id.scheduled__2024-07-18T09_00_00%2B00_00_task_id.linehub_tvl_data_ingestion_attempt.4.log)
