### ISSUE TITLE
Gravita Subgraph logic issue - doesnt use block number

### ISSUE THREAD

**Issue by nitish-91** [delta-hq/l2-lxp-liquidity-reward#49]
@spider-g please create a PR to update gravita code. The function getUserTVLByBlock in index.ts does take the block number input but doesnt use it while calling the subgraph query. 

For each input block number, we need tvl at that block number only. Right now that is not happening. You can refer this PR 

https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/14

**Comment by spider-g** [comment]
Solved by PR #55

**Comment by 0xroll** [comment]
@spider-g can you check your subgraph for stability pool? number seems to be off according to the output from the merged pr

**Comment by spider-g** [comment]
can you elaborate on what you think seems off? I checked the reported number against the contract and it looks okay
