### ISSUE TITLE
Velocore - Function to be implemented

### ISSUE THREAD

**Issue by nitish-91** [delta-hq/l2-lxp-liquidity-reward#52]
@velocore can you please implement the function as mentioned in the readme
https://github.com/delta-hq/l2-lxp-liquidity-reward/tree/main?tab=readme-ov-file#code-changes-expected

You can use this PR as reference
https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/14

**Comment by velocore** [comment]
@nitish-91 We've just made a PR for this issue. Please check it out 🙂
