### ISSUE TITLE
Connext adapter returning unexpected data

### ISSUE THREAD

**Issue by RamonReis** [delta-hq/l2-lxp-liquidity-reward#53]
When querying for block 'B', the adapter is returning data for different blocks.
On the image, the top data frame is the data returned by the adapter, the data frame on the bottom contains the queried blocks.

![image](https://github.com/delta-hq/l2-lxp-liquidity-reward/assets/3669322/9a12e0cb-eaba-4000-b1e8-351f55481f2c)

**Comment by RamonReis** [comment]
The issue persists.
If a single block number is inputted, all outputs must refer to the inputted block number value.
But multiple block numbers are present on the output when a single block number is inputted

**Comment by nitish-91** [comment]
@LayneHaber please check this

**Comment by LayneHaber** [comment]
should the timestamp be the block timestamp?

if its the timestamp of the latest subgraph update instead of the block, fixes should be in #104

**Comment by nitish-91** [comment]
@LayneHaber yes, the timestamp should be block timestamp in epoch format
