### ISSUE TITLE
$GRAI balance from adapter is not matching

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#75]
@spider-g 

still not getting matched balance for stability pool balance

can you check?

some addresses that ive checked and they dont match debank's number

0xaccafcb7d7c38ec39ab2cd0b9c54f9f058cc0dbd
0x2d32c55265da1e1b8cbe073b0c3a5d210b1d63db
0x5ec8cd4881eba87279f5f243eb89ea9383e677c6
0x5580ba66f8d6dc71adb0ca1d1c6b3d142ff7aaca

please make sure that all events that is affecting the balance is accounted for. we can also discuss this on tg (@jh_onchain)

can you also provide the subgraph repo link

**Comment by spider-g** [comment]
Hey there, GRAI deposited in the StabilityPool gets exchanged for collateral assets (with a slight discount) during liquidation events. When users withdraw, they receive their GRAI along with gains from these liquidations. The connector we have for you only displays the nominal (initial) deposits, not the compound gains from those exchange events. I believe that's a fair representation of the deposited value, considering those liquidations don't happen often.

**Comment by 0xroll** [comment]
@spider-g is this something that we cannot account for? was hoping to get exact match with the amount on debank too

**Comment by spider-g** [comment]
I'm afraid not, our subgraphs don't capture those liquidation events
individually.
Would you rather just use the numbers that come from debank? I'm okay with
that too.
But I assume that because liquidations are rare, the numbers won't differ
much.

Em ter., 30 de abr. de 2024 às 01:14, 0xroll ***@***.***>
escreveu:

**Comment by 0xroll** [comment]
@spider-g yes it will be good to have the numbers matching (that is their correct balance at the specific block)

is the plan to change the adapter to doing rpc calls / debank api?

concerned about the time needed to get the full data for each run (we should be running the codes hourly)

**Comment by spider-g** [comment]
Oh I meant in case you wanted to fetch from debank directly, I wasn't
opposed to that.
If you don't mind, I'd rather leave the numbers as they are now,
considering the difference is not significant.

Em qua., 1 de mai. de 2024 às 03:27, 0xroll ***@***.***>
escreveu:

**Comment by 0xroll** [comment]
@spider-g ok make sense, since GRAI are exchanged to the liquidated assets (and being classified as rewards in debank).

i think we are good to go for gravitas, thanks!
