### ISSUE TITLE
celer - balance should be in raw amount 

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#77]
@MHHard 

hey, currently celer pr is returning real amount (with decimals)

can we have the raw amount instead

**Comment by Dominator008** [comment]
It should be returning the raw amount now.

**Comment by nitish-91** [comment]
@Dominator008 didnt see any code change. Did you change it in the subgraph ?

**Comment by Dominator008** [comment]
We made the change in our backend API implementation.
