### ISSUE TITLE
Mendi error `Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by RamonReis** [delta-hq/l2-lxp-liquidity-reward#78]
When executing the adapter for a single block number the following error is occurring (e.g.):

```
Block: 3976979
Tokens:  525961
Account Borrows:  93572
An error occurred for block [object Object]: RangeError: Maximum call stack size exceeded
    at adapters/mendi/dist/index.js:82:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by nitish-91** [comment]
@gathonwar can you please look into this.

**Comment by gathonwar** [comment]
I think the problem is this:
https://stackoverflow.com/questions/61740599/rangeerror-maximum-call-stack-size-exceeded-with-array-push
