### ISSUE TITLE
Syncswap - data issue

### ISSUE THREAD

**Issue by 0xroll** [delta-hq/l2-lxp-liquidity-reward#82]
hi @amedrontadora 

have just looked at the pr / data from adapter.

there are a couple of issues here : 
1)  data from adapter doesnt seem to be correct, seems like quite abit of data is missing **
2)  token_address column should always be the underlying token address . eg (address of usdc / usdt / weth)
3)  if there are ETH pairs , please use  WETH address 0xe5d7c2a44ffddf6b295a15c148167daaaf5cf34f
4)  token amount should be in raw amount (no decimals)
5) price should also be in underlying token price, but its fine if you just change it to null for this PR change
 
 ** from syncswap docs , you guys are CPMM (similar codebase as uniswap v2) , can you refer to this [pr made by sushi](https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/37/files) to make the changes?
 
 i dont think concentrated liquidity model is on syncswap yet, so you probably wont need the v3 codes in sushi's pr.
 
 if you have any questions please feel free to dm me on tg @jh_onchain

**Comment by amedrontadora** [comment]
I refactored the adapter according to the request with reference to sushiswap
https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/87

**Comment by nitish-91** [comment]
@amedrontadora we are seeing that the input block number is not correctly used and we get many other block number's related data for each input.

**Comment by amedrontadora** [comment]
@nitish-91 Can you share more details? I don't understand what went wrong

**Comment by nitish-91** [comment]
@amedrontadora not seeing this issue anymore.
